climbjios-sg/climbjios-app

backend/src/auth/googleOauth/googleOauth.module.ts, backend/src/auth/googleOauth/googleOauth.strategy.ts, backend/src/auth/jwtAuth/jwtAuth.module.ts, backend/src/auth/jwtAuth/jwtAuth.strategy.ts, backend/src/utils/constants/constants.module.ts, backend/src/utils/constants/constants.service.ts
=> refactor(backend): abstract constants logic into ConstantsModule

README.md, frontend/src/pages/dashboard/jios/edit/index.tsx, frontend/src/pages/dashboard/jios/form/JiosForm.tsx, frontend/src/pages/dashboard/jios/list/EmptyJiosContent.tsx, frontend/src/pages/dashboard/jios/list/allJios/JioCardList.tsx, frontend/src/pages/dashboard/jios/list/index.tsx, frontend/src/pages/dashboard/jios/list/myJios/CloseMyJioDialog.tsx, frontend/src/pages/dashboard/jios/list/myJios/MyJioCard.tsx, frontend/src/pages/dashboard/jios/list/myJios/MyJioCardList.tsx
- Add Create Jio Button to empty state
https://github.com/climbjios-sg/climbjios-app/issues/24
=> Fix UI Empty State

frontend/src/pages/dashboard/jios/list/index.tsx, frontend/src/pages/dashboard/profile/index.tsx
Fix padding bottom
Current: UI has a big padding bottom
Solution: Use a smaller padding bottom and min height
=> fix: padding bottom

frontend/src/pages/dashboard/jios/list/allJios/JioCard.tsx
=> refactor: shift open to climb

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, frontend/src/components/FloatingBottomCard.tsx, frontend/src/components/hook-form/RHFDatePicker.tsx, frontend/src/components/hook-form/RHFRadioGroup.tsx, frontend/src/components/hook-form/RHFSelect.tsx, frontend/src/components/hook-form/RHFTextField.tsx, frontend/src/pages/dashboard/jios/create/index.tsx, frontend/src/pages/dashboard/jios/edit/index.tsx, frontend/src/pages/dashboard/jios/form/JiosCreateEditForm.tsx, frontend/src/pages/dashboard/jios/form/JiosSearchForm.tsx, frontend/src/pages/dashboard/jios/form/utils.ts, frontend/src/pages/dashboard/jios/list/allJios/JioCard.tsx, frontend/src/pages/dashboard/jios/list/allJios/JioCardList.tsx, frontend/src/pages/dashboard/jios/list/index.tsx, frontend/src/pages/dashboard/jios/list/myJios/CloseMyJioDialog.tsx, frontend/src/pages/dashboard/jios/list/myJios/MyJioCard.tsx, frontend/src/pages/dashboard/jios/list/utils.ts, frontend/src/pages/dashboard/jios/search/index.tsx, frontend/src/utils/formatTime.ts
Fixed many things...
- Fix Create Jio not working
- Refactor & fixed form validation for CreateEdit and Search Jio form
- Display price on jio cards
- Fix incorrect datetime display by removing utc offset function, it turned out the browser timing is alr correct
- Scroll to error in form
=> Fix jioform

frontend/src/components/FloatingBottomCard.tsx, frontend/src/pages/auth/Login.tsx, frontend/src/pages/dashboard/MainApp.tsx, frontend/src/pages/dashboard/jios/create/index.tsx, frontend/src/pages/dashboard/jios/edit/index.tsx, frontend/src/pages/dashboard/jios/form/JiosCreateEditForm.tsx, frontend/src/pages/dashboard/jios/form/JiosSearchForm.tsx, frontend/src/pages/dashboard/jios/list/allJios/JioCardList.tsx, frontend/src/pages/dashboard/jios/list/index.tsx, frontend/src/routes/paths.ts
- Fix comments stated in https://github.com/climbjios-sg/climbjios-app/pull/49
- Fix zIndex for FloatingBottomCard
Before zIndex fix:
After zIndex fix:
=> fix jio form nits

backend/src/posts/dtos/searchPost.dto.ts
Add `isClosed` to search params
#52
=> fix(search-posts): add isClosed to search params and default to false

landing/src/partials/Footer.jsx
- Fix GitHub Footer URL
- Change `to` to `href`
=> fix: footer github

.gitignore, frontend/src/config.ts
Fixed telegram regex. Should now work for all valid Telegram usernames
[#56 ](https://github.com/climbjios-sg/climbjios-app/issues/56)
=> fix: Telegram regex

landing/README.md, landing/src/partials/Footer.jsx, landing/src/partials/Header.jsx
- Fixes
- Weird margin right issue on mobile
- Add
- ClimbJios Logo in mobile nav 
Fixes
=> fix: mobile nav and mr issue

frontend/src/components/SupportButton.tsx, frontend/src/config.ts, frontend/src/pages/dashboard/jios/list/ErrorContent.tsx, frontend/src/pages/dashboard/jios/list/allJios/JioCard.tsx, frontend/src/pages/dashboard/jios/list/myJios/MyJioCardList.tsx
- Jio support button didn't have a link
- I added my telegram url to the button
- Also refactored out the error content component
=> fix: jio support button

frontend/src/utils/formatTime.ts
- Format time should include minute
Before
After
=> fix: format time include min

backend/src/database/migrations/20221018054737_add-bio-to-user-profiles.ts, backend/src/database/models/userProfile.model.ts, backend/src/user/dtos/patchUserProfile.dto.ts
=> feat: add bio user profile field to backend

backend/src/auth/googleOauth/googleOauth.strategy.ts, backend/src/auth/telegramOauth/telegramOauth.strategy.ts, backend/src/database/migrations/20221019043126_add-oauth-name-to-users-table.ts, backend/src/database/models/user.model.ts, backend/src/database/seeds/02-Users.ts, backend/src/database/seeds/09-User_Profiles.ts
=> feat: update BE onboarding flow to fit new requirement

frontend/src/@types/user.ts, frontend/src/components/hook-form/RHFAutoMultiSelect.tsx, frontend/src/components/hook-form/RHFSelect.tsx, frontend/src/components/hook-form/RHFTextField.tsx, frontend/src/config.ts, frontend/src/hooks/dev/useDevWatchForm.ts, frontend/src/pages/dashboard/jios/forms/JiosCreateEditForm.tsx, frontend/src/pages/onboarding/ClimbingCertForm.tsx, frontend/src/pages/onboarding/ClimbingGradesForm.tsx, frontend/src/pages/onboarding/DetailsForm.tsx, frontend/src/pages/onboarding/FavoriteGymsForm.tsx, frontend/src/pages/onboarding/index.tsx, frontend/src/services/avatar.ts, frontend/src/utils/authorizedAxios.ts, frontend/src/utils/axios.ts, frontend/src/utils/form.ts, frontend/src/utils/typeGuards.ts
=> feat: Add transformer to sanitize empty values

frontend/.gitignore, frontend/src/App.tsx, frontend/src/index.tsx, frontend/src/serviceWorker/ServiceWorker.tsx, frontend/src/serviceWorker/serviceWorkerRegistration.ts
https://user-images.githubusercontent.com/53928333/197329726-a8388c0c-c562-4ee4-a0c8-3f0af19c759f.mp4
=> feat: add service worker invalidation logic

frontend/src/@types/send.ts, frontend/src/@types/user.ts, frontend/src/pages/dashboard/jios/list/JioCardSkeleton.tsx, frontend/src/pages/dashboard/jios/list/allJios/JioCard.tsx, frontend/src/pages/dashboard/jios/list/utils.ts, frontend/src/pages/dashboard/profile/BioCard.tsx, frontend/src/pages/dashboard/profile/Sends.tsx, frontend/src/pages/profile/UserPublicProfile.tsx, frontend/src/routes/index.tsx, frontend/src/routes/paths.ts, frontend/src/utils/formatString.ts
- Added public profile page for user with placeholder values for missing fields, as designed in Figma.
- Updated Jio cards according to design in Figma.
#61 
#71
=> feat(profile-page): add public profile with placeholders and update jio card layout

frontend/src/pages/dashboard/jios/forms/JiosCreateEditForm.tsx, frontend/src/pages/dashboard/jios/list/allJios/JioCard.tsx, frontend/src/pages/dashboard/jios/list/myJios/MyJioCard.tsx, frontend/src/pages/dashboard/jios/list/utils.ts
Adding some styling fixes for jiocard
=> fix: fix jio card styles

frontend/src/@types/user.ts, frontend/src/pages/dashboard/profile/BioCard.tsx, frontend/src/utils/formatString.ts
Fix to change the following:
- Created new Certification type for SNCS certification
- Changed highestLeadClimbingGrade from string to be of type Grade, just like bouldering and top rope grades
=> fix: sncs certification in user type

frontend/src/pages/dashboard/jios/list/allJios/JioCard.tsx, frontend/src/pages/dashboard/profile/BioCard.tsx, frontend/src/pages/profile/UserPublicProfile.tsx
Previously, user profile shown when clicking on a JioCard is the current user's profile when instead it should be the Jio creator's user profile. This PR fixes this and displays the correct user.
=> fix: profile not displaying correct user

.github/workflows/ci-test.yaml, backend/src/auth/auth.controller.ts, backend/src/auth/googleOauth/googleOauth.strategy.ts, backend/src/database/daos/gyms/gyms.dao.service.ts, backend/src/database/daos/posts/posts.dao.service.ts, backend/src/database/daos/users/user.dao.service.ts, backend/src/database/models/user.model.ts, backend/src/database/models/userProfile.model.ts, backend/src/database/seeds/02-Users.ts, backend/src/gyms/gyms.service.ts, backend/src/posts/post.service.ts, backend/test/app.e2e-spec.ts, backend/test/helpers.ts, backend/test/mocks/MockTelegramOauthStrategy.ts
=> Add backend e2e tests

frontend/src/components/guards/CommonGuard.tsx, frontend/src/components/guards/NotAuthenticated.tsx, frontend/src/hooks/auth/useAuthState.ts, frontend/src/hooks/auth/useLogin.ts, frontend/src/hooks/guards/useAuthenticated.ts, frontend/src/hooks/guards/useCheckAuth.ts, frontend/src/hooks/guards/useCheckNotAuth.ts, frontend/src/hooks/guards/useCheckNotOnboarded.ts, frontend/src/hooks/guards/useCheckOnboarded.ts, frontend/src/hooks/guards/useGuard.ts, frontend/src/hooks/guards/useNotAuthenticated.ts, frontend/src/hooks/guards/useNotOnboarded.ts, frontend/src/hooks/guards/useOnboarded.ts, frontend/src/routes/index.tsx
=> feat: Disable notif on login and onboarding

frontend/src/components/StyledA.tsx, frontend/src/pages/onboarding/index.tsx, frontend/src/pages/publicProfile/index.tsx, frontend/src/routes/paths.ts, frontend/src/utils/common.ts
=> feat: add terms & privacy

frontend/src/components/a2hs/AddToHomeScreen.tsx
=> fix: iOS install prompt

frontend/package.json, frontend/src/authProviders/jwt.ts, frontend/yarn.lock
=> fix: refresh token flow when access token expires

backend/test/app.e2e-spec.ts, frontend/package.json, frontend/src/pages/onboarding/AvatarForm.tsx, frontend/yarn.lock
=> Compress image

frontend/src/@types/cache.ts, frontend/src/authProviders/jwt.ts, frontend/src/pages/dashboard/jios/list/allJios/JioCardList.tsx, frontend/src/service-worker.ts, frontend/src/serviceWorker/ServiceWorker.tsx
- implement cache at service worker layer
- images (s3 and website assets) with StaleWhileRevalidate strategy
- endpoints with NetworkFirst strategy
- online and offline notification toasts
=> feat: add offline functionality via service worker

frontend/src/components/BackBar.tsx, frontend/src/components/a2hs/AddToHomeScreen.tsx, frontend/src/components/guards/CommonGuard.tsx, frontend/src/components/profile/ProfileHeaderAndTabs.tsx, frontend/src/pages/dashboard/index.tsx, frontend/src/pages/dashboard/jios/list/index.tsx
- Fix add to home screen prompt
- Show only in jio card list component
- Add option to not show again
- Fix backbar styling
- Disable auto hide for profile beta
=> fix a2hs and styling

frontend/src/components/BackBar.tsx
minor fix, back bar remove auto hide threshold
=> fix: back bar

frontend/src/authProviders/jwt.ts, frontend/src/components/a2hs/AddToHomeScreen.tsx
- add 2 hs notifs popping up multiple times in prod
- fix is to remove deps array
- fix non working auth redirect
=> fix: add 2 hs notifs

frontend/src/pages/dashboard/profile/EditProfile.tsx
- Fix edit profile back button. Use backbar component.
=> fix: edit profile back bar

frontend/src/pages/dashboard/profile/MyProfile/AboutTab/index.tsx
- Minor fix change add to homescreen text
=> fix: add to home screen button text

frontend/src/config.ts
=> fix: video size

backend/src/database/daos/gyms/gyms.dao.service.ts, backend/src/database/seeds/01-Gyms.ts, backend/test/app.e2e-spec.ts, frontend/src/@types/beta.ts, frontend/src/components/NotistackProvider.tsx, frontend/src/components/Video.tsx, frontend/src/components/betas/BetaCardBase.tsx, frontend/src/components/betas/BetaInfiniteScroll.tsx, frontend/src/components/betas/WallAndColorIcon.tsx, frontend/src/components/betas/utils.ts, frontend/src/components/profile/ProfileBetas.tsx, frontend/src/hooks/services/useGetBetas.ts, frontend/src/hooks/services/useGetCreatorBetas.ts, frontend/src/hooks/services/useGetOptions.ts, frontend/src/pages/dashboard/betas/create/index.tsx, frontend/src/pages/dashboard/betas/form/BetaCreateEditForm.tsx, frontend/src/pages/dashboard/betas/list/index.tsx, frontend/src/pages/dashboard/jios/forms/JiosCreateEditForm.tsx, frontend/src/pages/dashboard/jios/forms/JiosSearchForm.tsx, frontend/src/pages/dashboard/jios/list/allJios/JioCardList.tsx, frontend/src/pages/error/NoTelegramUsernameError.tsx, frontend/src/pages/error/TelegramUsernameAndroid.tsx, frontend/src/pages/error/TelegramUsernameIOS.tsx, frontend/src/serviceWorker/ServiceWorker.tsx, frontend/src/services/betas.ts, frontend/src/store/reducers/index.ts, frontend/src/store/reducers/myLocalBetaVideos.ts
- Fix video upload, video not displayed issue
- Videos that are successfully uploaded are stored in redux, video will be rendered from redux data instead of fetched data
- Display wall type and color
- Note: Some colors don't look too nice, might want to creator a color dict to generate nice colors
- Add gym: BP (Tai Seng)
=> HotFix beta stuff

frontend/src/@types/color.ts, frontend/src/@types/index.ts, frontend/src/@types/pronoun.ts, frontend/src/@types/wall.ts, frontend/src/components/betas/BetaCardBase.tsx, frontend/src/components/betas/WallIcon.tsx, frontend/src/pages/dashboard/betas/create/index.tsx, frontend/src/services/betas.ts
Fix comments from https://github.com/climbjios-sg/climbjios-app/pull/151
=> fix: beta pr comments

backend/src/database/seeds/01-Gyms.ts, backend/test/app.e2e-spec.ts, frontend/src/components/betas/BetaCardBase.tsx, frontend/src/components/hook-form/RHFDatePicker.tsx, frontend/src/components/hook-form/RHFTextField.tsx, frontend/src/components/profile/BioCard.tsx, frontend/src/components/profile/ProfileHeader.tsx, frontend/src/components/profile/ProfileHeaderAndTabs.tsx, frontend/src/hooks/auth/useGetIdentity.ts, frontend/src/pages/dashboard/betas/list/index.tsx, frontend/src/pages/dashboard/profile/MyProfile/AboutTab/index.tsx, frontend/src/pages/dashboard/profile/MyProfile/index.tsx
Bug fixes
- Fixed by disabling scroll
- Fixed by specifying input format to dd/mm/yy
- Fix by showing skeleton
- Fix by removing defaultValue prop
#158 #159
=> Many Bug fixes

backend/src/betas/betas.service.ts, backend/src/database/daos/betas/betas.dao.service.ts, backend/src/database/models/beta.model.ts, frontend/src/components/MessageBar.tsx, frontend/src/components/betas/BetaInfiniteScroll.tsx, frontend/src/components/profile/ProfileBetas.tsx, frontend/src/pages/dashboard/betas/create/index.tsx, frontend/src/pages/dashboard/betas/list/index.tsx, frontend/src/store/reducers/messageBar.ts
- Fix infinite scroll for backend
- isLastPage and totalPages fields for beta pagination were wrong
- Fixed the data
=> fix: infinite scroll

frontend/src/components/guards/CommonGuard.tsx, frontend/src/hooks/guards/useCheckNotOnboarded.ts, frontend/src/hooks/guards/useGuard.ts, frontend/src/pages/dashboard/index.tsx, frontend/src/routes/index.tsx
* Push the redirection in dashboard to common guard
=> fix: redirect

frontend/src/components/guards/CommonGuard.tsx, frontend/src/hooks/useLocalStorage.ts
=> fix: use cb

frontend/src/components/guards/CommonGuard.tsx, frontend/src/hooks/guards/useCheckNotAuth.ts, frontend/src/hooks/guards/useGuard.ts, frontend/src/index.tsx, frontend/src/pages/dashboard/index.tsx
=> fix: debug

frontend/src/serviceWorker/ServiceWorker.tsx
Force service worker to auto update and reload the page
#175
=> feat: force service worker to auto update

frontend/src/components/betas/BetaCardBase.tsx, frontend/src/components/jios/JioCardHeader.tsx, frontend/src/hooks/useAddToHomeScreen.tsx, frontend/src/pages/dashboard/jios/forms/JiosCreateEditForm.tsx, frontend/src/pages/dashboard/jios/forms/JiosSearchForm.tsx
Add classnames to elements of interest for Google Tag Manager tracking
=> chore: add classnames for potential click tracking

CHANGELOG.md, README.md, frontend/package.json, frontend/src/config.ts, frontend/src/pages/auth/Login.tsx, frontend/src/pages/dashboard/profile/MyProfile/AboutTab/index.tsx
=> chore: add release info

frontend/src/components/addToHomeScreen/AddToHomeScreenButton.tsx, frontend/src/hooks/useAddToHomeScreen.tsx
Improved instructions for climbers to add to home screen
=> fix: make instructions clearer for a2hs

frontend/src/config.ts
=> fix: version number

frontend/src/pages/dashboard/jios/forms/JiosCreateEditForm.tsx
=> fix: optional note edit

backend/src/posts/post.service.ts, backend/test/app.e2e-spec.ts, frontend/src/pages/dashboard/jios/forms/JiosCreateEditForm.tsx
=> dev to main

landing/src/constants.js, landing/src/partials/PublicBeta.jsx
=> fix: tele url

CHANGELOG.md, README.md, backend/src/cronjob/cronjob.service.ts, backend/src/posts/post.service.ts, backend/src/utils/telegram/telegram.service.ts, frontend/package.json, frontend/src/components/Video.tsx, frontend/src/config.ts
=> dev to main v1.0.1

frontend/package.json, frontend/src/config.ts, frontend/src/pages/dashboard/jios/create/index.tsx, frontend/src/pages/dashboard/jios/list/search/index.tsx
- Fix search auto populate CreateEditJio form
- Change jiotype text to selling and buying
=> Fix search

backend/src/database/seeds/13-Add-Data.ts
- add seed data for gyms @chownces
=> fix: add seed data for gyms

backend/test/app.e2e-spec.ts
=> test: search

frontend/src/components/betas/BetaCardBase.tsx, frontend/src/components/betas/WallIcon.tsx, frontend/src/components/inputs/FilterSelect.tsx, frontend/src/components/inputs/MenuItemLabelWithIcon.tsx, frontend/src/components/inputs/SelectLabel.tsx, frontend/src/components/inputs/SelectWithIcon.tsx, frontend/src/pages/dashboard/betas/list/index.tsx, frontend/src/pages/dashboard/jios/list/search/index.tsx
- Use mui select button for beta filtering
- Clearable filters
=> Fix: Better UI for betas filter

backend/src/database/daos/posts/posts.dao.service.ts
- Change datetime filter to endDateTime >= new Date() instead of startDateTime
=> fix: date search

frontend/src/pages/dashboard/jios/create/index.tsx
- If datetime is autofilled, add a snackbar telling user so
=> fix: add snackbar text for autofill date time

frontend/src/pages/dashboard/jios/edit/index.tsx
=> fix: jio edit

landing/package.json, landing/src/App.jsx, landing/yarn.lock
Added Google Tag manager for landing page analytics
=> chore: add analytics to landing page

backend/src/posts/post.service.ts
Remove validation check for same date for patch post
=> fix: backend edit jio fail for empty date

README.md
Restore instructions on new features flow
=> docs: Restore readme new features flow

frontend/src/components/profile/ProfileHeader.tsx, frontend/src/pages/publicProfile/index.tsx
Add a "message" button to allow user to message another user on telegram
- Does not show on your own profile page
=> feature: Add button on public climber page to message them directly

frontend/src/pages/dashboard/profile/EditProfile.tsx, frontend/src/pages/onboarding/index.tsx
Moved required() method to the front for the username field (in onBoarding and EditProfile) so it's actually invoked
No issue for this
=> fix: required method first for username input

frontend/src/pages/dashboard/profile/EditProfile.tsx, frontend/src/pages/onboarding/index.tsx
As per title
No issue
https://user-images.githubusercontent.com/40333518/209465345-56928847-0ba8-4148-93da-f70aaed35871.mov
https://user-images.githubusercontent.com/40333518/209465461-ffa6c90b-e905-4426-aaa2-0fa7b993bf19.mov
=> feat: changed validation mode in onBoarding and EditProfile to onChange

frontend/src/components/Video.tsx
=> feat: preload none

frontend/src/components/Video.tsx
=> feat: video

frontend/src/pages/dashboard/gyms/GymSearch.tsx, frontend/src/pages/dashboard/index.tsx
1. Previous PR put the onClick on the pin icon, but not the entire `BottomNavigationAction`. Fixed that.
2. Updated gyms search tooltip to suggest searching by gym address as well.
=> more final tweaks for feat/f01 gym

backend/src/database/seeds/15-f01-add-gyms-passes.ts, frontend/src/pages/gymDetailsPage/GymPassesTab/GymPassesTab.tsx
1. Fixed Climb@T3 passes being tagged to Camp5 Utama
2. Added missing margin to no data for passes card
=> even more data and UI tweaks/fixes for f01/gym 

backend/src/database/seeds/15-f01-add-gyms-passes.ts, frontend/package.json, frontend/patches/react-infinite-scroll-component+6.1.0.patch, frontend/src/components/GrowableScroll.tsx, frontend/src/components/gymDetailsPage/GymPageLoader.tsx, frontend/src/pages/dashboard/gyms/list/GymGroupCard.tsx, frontend/src/pages/dashboard/index.tsx, frontend/src/pages/gymDetailsPage/GymDetailsPage.tsx, frontend/src/pages/gymDetailsPage/GymPageHeader.tsx, frontend/src/routes/index.tsx, frontend/yarn.lock
1. fixed jio page constantly refreshing when trying to scroll by moving `DashboardRouter` out of `Dashboard` (I was the one that put it there)
2. fixed tapping screen on `InfiniteScroll `component causing the side shadows to disappear as it sets `overlay: auto` automatically, so I patched the package to remove that.
3. fixed "New!" badge on gyms NavBar button reappearing by using localStorage instead of setState
4. fixed app freezing while `GymDetailsPage` loaded by removing the use of react-router's loader and using useRequest directly, and added a `GymDetailsPageLoader`.
=> final final fixes for feat/f01 gym initial deployment

frontend/src/components/profile/ProfileHeaderAndTabs.tsx
1. fix: MyProfile header doesn't touch left of screen
=> seriously, final fix for feat/f01 gym
